### ISSUE TITLE
Why dropout used on input data directly?

### ISSUE THREAD

**Issue by mrgloom** [mateuszbuda/ALL-CNN#1]
Why dropout used on input data directly?
https://github.com/mateuszbuda/ALL-CNN/blob/master/ALL_CNN_C_train_val.prototxt#L32

**Comment by mateuszbuda** [comment]
Refer to the paper: https://arxiv.org/pdf/1412.6806.pdf
Simple answer would be that it's applied to prevent overfitting.

**Comment by mrgloom** [comment]
I see:

> We applied dropout to the input image as well as af-
> ter each  pooling layer (or after  the layer replacing  the pooling layer  respectively).   The  dropout probabilities > were 20% for dropping out inputs and 50% otherwise.
